# Generated by Django 4.0.3 on 2022-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('foto', models.ImageField(null=True, upload_to='uploads/fotos')),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('calle', models.CharField(max_length=70, null=True)),
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
