# Generated by Django 4.0.3 on 2022-04-24 09:39

import cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(null=True, upload_to=cliente.models.url),
        ),
    ]
