# Generated by Django 4.0.3 on 2022-06-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='deleted',
        ),
    ]
