# Generated by Django 4.0.3 on 2022-06-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='deleted',
        ),
    ]
