# Generated by Django 4.0.3 on 2022-04-11 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arreglo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
