# Generated by Django 4.0.3 on 2022-06-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_arreglo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arreglo',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='deleted',
        ),
    ]
